#!/bin/sh
set -e
package_name=kcmshell5-tweaks
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/kcmshell5"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/kcmshell5"
;;
esac
exit 0
